# Estágio 1: Configuração do PostgreSQL
FROM postgres:latest

# Configuração do PostgreSQL
ENV POSTGRES_PASSWORD @@123
ENV POSTGRES_USER postgres

# Expõe a porta 5432 do PostgreSQL
EXPOSE 5432

# Copiar scripts SQL para inicializar o banco de dados (se necessário)
# COPY db/init.sql /docker-entrypoint-initdb.d/

# Executa o PostgreSQL em primeiro plano
CMD ["postgres"]
















